{% set version = "2019.10.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prodlim
  version: {{ version|replace("-", "_") }}

source:
  fn: prodlim_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/prodlim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prodlim/prodlim_{{ version }}.tar.gz
  sha256: e604f0c2028958f4d813e7c209c8c888b75c5118740c5c6564c51f63fe755e67

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival

test:
  commands:
    - $R -e "library('prodlim')"           # [not win]
    - "\"%R%\" -e \"library('prodlim')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=prodlim
  license: GPL (>= 2)
  summary: Fast and user friendly implementation of nonparametric estimators for censored event
    history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
