{% set version = "2025.04.28" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-prodlim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prodlim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prodlim/prodlim_{{ version }}.tar.gz
  sha256: 62b7049aeb947dd54f1ccb210c111ae50eb7461b8c9942601e09a1a10721fc3a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-data.table                 # [build_platform != target_platform]
    - r-diagram                    # [build_platform != target_platform]
    - r-kernsmooth                 # [build_platform != target_platform]
    - r-lava                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-survival                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-diagram
    - r-kernsmooth
    - r-lava
    - r-rcpp >=0.11.5
    - r-survival
  run:
    - r-base
    - r-data.table
    - r-diagram
    - r-kernsmooth
    - r-lava
    - r-rcpp >=0.11.5
    - r-survival

test:
  commands:
    - $R -e "library('prodlim')"           # [not win]
    - "\"%R%\" -e \"library('prodlim')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=prodlim
  license: GPL-2.0-or-later
  summary: Fast and user friendly implementation of nonparametric estimators for censored event history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
