{% set version = "2019.11.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-prodlim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/prodlim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/prodlim/prodlim_{{ version }}.tar.gz
  sha256: 6809924f503a14681de84730489cdaf9240d7951c64f5b98ca37dc1ce7809b0f

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-kernsmooth
    - r-rcpp >=0.11.5
    - r-lava
    - r-survival

test:
  commands:
    - $R -e "library('prodlim')"           # [not win]
    - "\"%R%\" -e \"library('prodlim')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=prodlim
  license: GPL-2.0-or-later
  summary: Fast and user friendly implementation of nonparametric estimators for censored event
    history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: prodlim
# Title: Product-Limit Estimation for Censored Event History Analysis
# Version: 2019.10.13
# Author: Thomas A. Gerds
# Description: Fast and user friendly implementation of nonparametric estimators for censored event history (survival) analysis. Kaplan-Meier and Aalen-Johansen method.
# Depends: R (>= 2.9.0)
# Imports: Rcpp (>= 0.11.5), stats, grDevices, graphics, survival, KernSmooth, lava
# LinkingTo: Rcpp
# Maintainer: Thomas A. Gerds <tag@biostat.ku.dk>
# License: GPL (>= 2)
# Packaged: 2019-11-03 17:32:42 UTC; tag
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-11-03 18:30:02 UTC
