appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: mLZbXr0/kT1lwVno8NPgrJUOp83vQIBSsYP3vwMaBFra8GiOWrri95PKVxjNNlO9Y/BduvMbxGjRAHbdG/5GSXugKykAHM90K6mpTzSFRH8gXCVRwVvyRXlA5sm9qhh2l+llVcCc0XgGela3iSm6fgEUqRuB0EbEUQh0UaowoecIy4Vx4fGLGs4WR4EaD6w6BZhOE8dEiX+Q0BAKgFXRyz3tEqszq3IRg1fBn8RI5AFXXrvXSkjnSQ4OAE0Vo7+E8hXpoZFKIqcQFWPfaPA85tqhKkUuPAPF77PFs0pNia5zkrOHZFLiU71pEJA6tqawC1cuiTMzImbdD8coEP0QE9k7uiPhoWAKJZoVSDUXJBZ0rDFau2RVqZLXOhRFZ2tksNQ76tWsjbuNlmzBE/ggqYVtOlp8X6sbCPKGTcQ+r9PsEO50MjozT5se8aF/ESraeYdGnZPbk7Gc9C6sRB9vkuy0J/ZYP7j3mrBkBUGEl769w0RRnMxwYrxcY1IBBRVthQJLRnaHHfGoxZ20FQLGm2E+2c83jBh/m0/O8rsOYAJodn/Dn5T6UpDsdw9iYFHHnW9lygmybJ90ef25YJBrJEpPHAsydcA3rkZdoA/6GI0II6hMCEnR/JFWwo3+asF/+48ZfR/vINWt3hRgBlgTClU4oRxe7e5XsqOo4Ww05ac=}
