travis:
  secure:
    BINSTAR_TOKEN: iS42Pj+se8KA2UjkU0l0SPLtp718k9PTQjc5GbMzMzw3h1HJRedDl7YwwOCRXA5lOnmU28lPAKkrtx/U3+1Y1U5zomcD3uxIa2TXm6+pXwrWGdnxrk7ZWo+UKhY1ND1Au1pBo8P3B1bjg9TE5Ox28jBP/H4xSx+vfbT6cgWLQRMA9xPOFHSSQwUaj7YfTCHHGgVKSLq6WLasqemUPB9ovIxgS6sApBBpmsm/CqinJ1apuHcP9Wc4XXcznB1fRpzVl0R+Ag9KYd+o+fkKubqYrQje7sOoDwa+BYHlX39LUK+oA33tki5dvLibv46QH1iQvahijAZ86vyW/w568y1rE6vfsCupu4WieUvB5nu7g4M2eDUg5M2KoveXY4oRTgrXO8UVsmBEL2REwKOxQRvcoak0MK2qSvKFy5zOnyKjviyk8IyRlvWWC2SO4zswLQH5MFcU+0gwDVjSQEd7iL6eNLth44Fim5BCNZhljdH5OYcNsQhS6rGHeHpBesFAIN3BkGe9+nzOZLrTYbZYQGw7TN7Pu6hZskkGbisT0d/dBMcjOiWgnmcmIg5zax0vIe2fW7ILMBxLXRaTfoq7XreUR5DsXDkkGhlotZBVDnjv75esGZjvk62WgVJYVisVqyKretIXFNZUU2FCRDvMgZJkhFEDy7QOXHfCaVaVt/Z/1tc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
